[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async_zip = { workspace = true, features = [
    "deflate",
    "deflate64",
    "tokio-fs",
] }
reqwest = { workspace = true }
strum = { workspace = true, features = ["derive"] }
regex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["io"] }
chrono = { workspace = true }
urlencoding = { workspace = true }
stl_io = { workspace = true }
threemf = { workspace = true }
image = { workspace = true, features = ["png", "jpeg"] }
libmeshthumbnail = { workspace = true }
vek = { workspace = true }
content_disposition = { workspace = true }
futures = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
