[package]
name = "db"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bitflags = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio", "chrono"] }
indexmap = { workspace = true }
itertools = { workspace = true }
strum = { workspace = true, features = ["derive"] }
password-auth = { workspace = true }
