[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true, features = ["json", "multipart"] }
axum-extra = { workspace = true, features = ["query"] }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "process"] }
tokio-util = { workspace = true, features = ["io"] }
axum-login = { workspace = true }
password-auth = { workspace = true }
db = { workspace = true }
service = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
axum-messages = { workspace = true }
time = { workspace = true }
tower-http = { workspace = true, features = ["fs", "compression-gzip"] }
tower-sessions = { workspace = true, features = ["signed"] }
tower-sessions-sqlx-store = { workspace = true, features = ["sqlite"] }
async_zip = { workspace = true, features = ["full"] }
htmlescape = { workspace = true }
